name: MsCore
version: '${project.version}'
main: me.thatonedevil.mscore.MsCore
authors: [ ThatOneDevil ]
description: Pugin for Mellow's Modded smp
commands:
  getPlayerData:
    description: Gets player data from sql Database
    permission: Mscore.admin
    permission-message: No
  setPlayerData:
    description: sets player data
    permission: Mscore.admin
    permission-message: No
  resetPlayerData:
    description: resets player data
    permission: Mscore.admin
    permission-message: No
  RevivePlayer:
    description: revives a  player
    permission: Mscore.admin
    permission-message: No
  msCoreVanish:
    description: Vanish
    permission: Mscore.admin
    permission-message: No
  ResetAllData:
    description: Resets all data can only be run by console
    permission: Mscore.admin
    permission-message: No
